// ==========================================================================
// data.js — Data master FSS & APAR
// Sumber: DATA_FSS___APAR_-_Copy.xlsx (sheet "APAR")
// Setiap baris dengan "kode" terisi = 1 alat yang punya QR/barcode.
// Baris tanpa "kode" ikut ditampilkan di rekap/export tapi tidak bisa discan
// (id nya dibuat otomatis: row<n>) sampai kode aslinya diisi di file sumber.
// ==========================================================================
const APAR_DATA = [
  {
    "no": 1,
    "ruangan": "Pos Security NETRE LT.1",
    "gedung": "POP/NETRE",
    "lantai": 1,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "Dry Chemical Powder",
    "kode": "110",
    "id": "110"
  },
  {
    "no": 2,
    "ruangan": "Pos Security NETRE LT.1",
    "gedung": "POP/NETRE",
    "lantai": 1,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "CO2",
    "kode": "111",
    "id": "111"
  },
  {
    "no": 3,
    "ruangan": "Teras NETRE LT.1",
    "gedung": "POP/NETRE",
    "lantai": 1,
    "merk": "BUCKEYE",
    "kapasitas": "125 Lb",
    "jenisGas": "Dry Chemical Powder",
    "kode": "112",
    "id": "112"
  },
  {
    "no": 4,
    "ruangan": "Lobby NETRE LT.1",
    "gedung": "POP/NETRE",
    "lantai": 1,
    "merk": "FIREFIX",
    "kapasitas": "5 kg",
    "jenisGas": "CO2",
    "kode": "113",
    "id": "113"
  },
  {
    "no": 5,
    "ruangan": "MDF NETRE LT.1",
    "gedung": "POP/NETRE",
    "lantai": 1,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "Dry Chemical Powder",
    "kode": "114",
    "id": "114"
  },
  {
    "no": 6,
    "ruangan": "MDF NETRE LT.1",
    "gedung": "POP/NETRE",
    "lantai": 1,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "CO2",
    "kode": "115",
    "id": "115"
  },
  {
    "no": 7,
    "ruangan": "Rectifier NETRE LT.1",
    "gedung": "POP/NETRE",
    "lantai": 1,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "CO2",
    "kode": "116",
    "id": "116"
  },
  {
    "no": 8,
    "ruangan": "Rectifier NETRE LT.1",
    "gedung": "POP/NETRE",
    "lantai": 1,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "CO2",
    "kode": "117",
    "id": "117"
  },
  {
    "no": 9,
    "ruangan": "Rectifier NETRE LT.1",
    "gedung": "POP/NETRE",
    "lantai": 1,
    "merk": "FIREFIX",
    "kapasitas": "5 kg",
    "jenisGas": "CO2",
    "kode": "118",
    "id": "118"
  },
  {
    "no": 10,
    "ruangan": "Trafo NETRE LT.1",
    "gedung": "POP/NETRE",
    "lantai": 1,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "Dry Chemical Powder",
    "kode": "119",
    "id": "119"
  },
  {
    "no": 11,
    "ruangan": "Cubical NETRE LT.1",
    "gedung": "POP/NETRE",
    "lantai": 1,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "CO2",
    "kode": "120",
    "id": "120"
  },
  {
    "no": 12,
    "ruangan": "Baterai Kering 1 NETRE LT.1",
    "gedung": "POP/NETRE",
    "lantai": 1,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "Dry Chemical Powder",
    "kode": "121",
    "id": "121"
  },
  {
    "no": 13,
    "ruangan": "Baterai Kering 1 NETRE LT.1",
    "gedung": "POP/NETRE",
    "lantai": 1,
    "merk": "FIREFIX",
    "kapasitas": "5 kg",
    "jenisGas": "CO2",
    "kode": "122",
    "id": "122"
  },
  {
    "no": 14,
    "ruangan": "Baterai Basah 1 NETRE LT.1",
    "gedung": "POP/NETRE",
    "lantai": 1,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "Dry Chemical Powder",
    "kode": "123",
    "id": "123"
  },
  {
    "no": 15,
    "ruangan": "Baterai Kering 2 NETRE LT.1",
    "gedung": "POP/NETRE",
    "lantai": 1,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "Dry Chemical Powder",
    "kode": "124",
    "id": "124"
  },
  {
    "no": 16,
    "ruangan": "Baterai Kering 2 NETRE LT.1",
    "gedung": "POP/NETRE",
    "lantai": 1,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "CO2",
    "kode": "125",
    "id": "125"
  },
  {
    "no": 17,
    "ruangan": "Lobby NETRE LT.2",
    "gedung": "POP/NETRE",
    "lantai": 2,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "CO2",
    "kode": "126",
    "id": "126"
  },
  {
    "no": 18,
    "ruangan": "UPS NETRE LT.2",
    "gedung": "POP/NETRE",
    "lantai": 2,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "CO2",
    "kode": "127",
    "id": "127"
  },
  {
    "no": 19,
    "ruangan": "STP NETRE LT.2",
    "gedung": "POP/NETRE",
    "lantai": 2,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "CO2",
    "kode": "128",
    "id": "128"
  },
  {
    "no": 20,
    "ruangan": "Koridor NETRE LT.2",
    "gedung": "POP/NETRE",
    "lantai": 2,
    "merk": "FIREFIX",
    "kapasitas": "5 kg",
    "jenisGas": "CO2",
    "kode": "129",
    "id": "129"
  },
  {
    "no": 21,
    "ruangan": "OLT NETRE LT.2",
    "gedung": "POP/NETRE",
    "lantai": 2,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "CO2",
    "kode": "130",
    "id": "130"
  },
  {
    "no": 22,
    "ruangan": "FTM NETRE LT.2",
    "gedung": "POP/NETRE",
    "lantai": 2,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "CO2",
    "kode": "131",
    "id": "131"
  },
  {
    "no": 23,
    "ruangan": "Lobby NETRE LT.3",
    "gedung": "POP/NETRE",
    "lantai": 3,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "Dry Cemical Powder",
    "kode": "132",
    "id": "132"
  },
  {
    "no": 24,
    "ruangan": "Data Center NETRE LT.3",
    "gedung": "POP/NETRE",
    "lantai": 3,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "CO2",
    "kode": "133",
    "id": "133"
  },
  {
    "no": 25,
    "ruangan": "Data Center NETRE LT.3",
    "gedung": "POP/NETRE",
    "lantai": 3,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "CO2",
    "kode": "134",
    "id": "134"
  },
  {
    "no": 26,
    "ruangan": "Data Center NETRE LT.3",
    "gedung": "POP/NETRE",
    "lantai": 3,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "CO2",
    "kode": "135",
    "id": "135"
  },
  {
    "no": 27,
    "ruangan": "Data Center NETRE LT.3",
    "gedung": "POP/NETRE",
    "lantai": 3,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "CO2",
    "kode": "136",
    "id": "136"
  },
  {
    "no": 28,
    "ruangan": "Data Center NETRE LT.3",
    "gedung": "POP/NETRE",
    "lantai": 3,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "CO2",
    "kode": "137",
    "id": "137"
  },
  {
    "no": 29,
    "ruangan": "NGN NETRE LT.3",
    "gedung": "POP/NETRE",
    "lantai": 3,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "CO2",
    "kode": "138",
    "id": "138"
  },
  {
    "no": 30,
    "ruangan": "NGN NETRE LT.3",
    "gedung": "POP/NETRE",
    "lantai": 3,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "CO2",
    "kode": "139",
    "id": "139"
  },
  {
    "no": 31,
    "ruangan": "NGN NETRE LT.3",
    "gedung": "POP/NETRE",
    "lantai": 3,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "CO2",
    "kode": "140",
    "id": "140"
  },
  {
    "no": 32,
    "ruangan": "NGN NETRE LT.3",
    "gedung": "POP/NETRE",
    "lantai": 3,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "CO2",
    "kode": "141",
    "id": "141"
  },
  {
    "no": null,
    "ruangan": "Panel NETRE LT.3",
    "gedung": "POP/NETRE",
    "lantai": 3,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "CO2",
    "kode": "142",
    "id": "142"
  },
  {
    "no": null,
    "ruangan": "Panel NETRE LT.3",
    "gedung": "POP/NETRE",
    "lantai": 3,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "Dry Cemical Powder",
    "kode": "143",
    "id": "143"
  },
  {
    "no": null,
    "ruangan": "Lobby NETRE LT.4",
    "gedung": "POP/NETRE",
    "lantai": 4,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "CO2",
    "kode": "144",
    "id": "144"
  },
  {
    "no": null,
    "ruangan": "Personil NETRE LT.4",
    "gedung": "POP/NETRE",
    "lantai": 4,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "Dry Cemical Powder",
    "kode": "145",
    "id": "145"
  },
  {
    "no": null,
    "ruangan": "Sentral NETRE LT.4",
    "gedung": "POP/NETRE",
    "lantai": 4,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "CO2",
    "kode": "146",
    "id": "146"
  },
  {
    "no": null,
    "ruangan": "Sentral NETRE LT.4",
    "gedung": "POP/NETRE",
    "lantai": 4,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "CO2",
    "kode": "147",
    "id": "147"
  },
  {
    "no": null,
    "ruangan": "Flexi NETRE LT.4",
    "gedung": "POP/NETRE",
    "lantai": 4,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "CO2",
    "kode": "148",
    "id": "148"
  },
  {
    "no": null,
    "ruangan": "Flexi NETRE LT.4",
    "gedung": "POP/NETRE",
    "lantai": 4,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "CO2",
    "kode": "149",
    "id": "149"
  },
  {
    "no": null,
    "ruangan": "Metro NETRE LT.4",
    "gedung": "POP/NETRE",
    "lantai": 4,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "CO2",
    "kode": "150",
    "id": "150"
  },
  {
    "no": null,
    "ruangan": "Metro NETRE LT.4",
    "gedung": "POP/NETRE",
    "lantai": 4,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "CO2",
    "kode": "151",
    "id": "151"
  },
  {
    "no": null,
    "ruangan": "Lobby NETRE LT.5",
    "gedung": "POP/NETRE",
    "lantai": 5,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "CO2",
    "kode": "152",
    "id": "152"
  },
  {
    "no": null,
    "ruangan": "Personil NETRE LT.5",
    "gedung": "POP/NETRE",
    "lantai": 5,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "Dry Cemical Powder",
    "kode": "153",
    "id": "153"
  },
  {
    "no": null,
    "ruangan": "BTS Flexi NETRE LT.5",
    "gedung": "POP/NETRE",
    "lantai": 5,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "CO2",
    "kode": "154",
    "id": "154"
  },
  {
    "no": null,
    "ruangan": "Space NETRE LT.5",
    "gedung": "POP/NETRE",
    "lantai": 5,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "CO2",
    "kode": "155",
    "id": "155"
  },
  {
    "no": null,
    "ruangan": "Monitoring NETRE LT.5",
    "gedung": "POP/NETRE",
    "lantai": 5,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "CO2",
    "kode": "156",
    "id": "156"
  },
  {
    "no": null,
    "ruangan": "Transmisi NETRE LT.5",
    "gedung": "POP/NETRE",
    "lantai": 5,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "CO2",
    "kode": "157",
    "id": "157"
  },
  {
    "no": null,
    "ruangan": "Transmisi NETRE LT.5",
    "gedung": "POP/NETRE",
    "lantai": 5,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "CO2",
    "kode": "158",
    "id": "158"
  },
  {
    "no": null,
    "ruangan": "Lobby NETRE LT.6",
    "gedung": "POP/NETRE",
    "lantai": 6,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "CO2",
    "kode": "159",
    "id": "159"
  },
  {
    "no": null,
    "ruangan": "Personil NETRE LT.6",
    "gedung": "POP/NETRE",
    "lantai": 6,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "Dry Cemical Powder",
    "kode": "160",
    "id": "160"
  },
  {
    "no": null,
    "ruangan": "Lorong NETRE LT.6",
    "gedung": "POP/NETRE",
    "lantai": 6,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "CO2",
    "kode": "161",
    "id": "161"
  },
  {
    "no": null,
    "ruangan": "Lorong NETRE LT.6",
    "gedung": "POP/NETRE",
    "lantai": 6,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "CO2",
    "kode": "162",
    "id": "162"
  },
  {
    "no": null,
    "ruangan": "Lorong NETRE LT.6",
    "gedung": "POP/NETRE",
    "lantai": 6,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "CO2",
    "kode": "163",
    "id": "163"
  },
  {
    "no": null,
    "ruangan": "Lorong NETRE LT.6",
    "gedung": "POP/NETRE",
    "lantai": 6,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "CO2",
    "kode": "164",
    "id": "164"
  },
  {
    "no": null,
    "ruangan": "IPTV NETRE LT.6",
    "gedung": "POP/NETRE",
    "lantai": 6,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "CO2",
    "kode": "165",
    "id": "165"
  },
  {
    "no": null,
    "ruangan": "IPTV NETRE LT.6",
    "gedung": "POP/NETRE",
    "lantai": 6,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "CO2",
    "kode": "166",
    "id": "166"
  },
  {
    "no": null,
    "ruangan": "NGN NETRE LT.6",
    "gedung": "POP/NETRE",
    "lantai": 6,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "CO2",
    "kode": "167",
    "id": "167"
  },
  {
    "no": null,
    "ruangan": "NGN NETRE LT.6",
    "gedung": "POP/NETRE",
    "lantai": 6,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "CO2",
    "kode": "168",
    "id": "168"
  },
  {
    "no": null,
    "ruangan": "NGN NETRE LT.6",
    "gedung": "POP/NETRE",
    "lantai": 6,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "CO2",
    "kode": "169",
    "id": "169"
  },
  {
    "no": null,
    "ruangan": "Monitor NETRE LT.6",
    "gedung": "POP/NETRE",
    "lantai": 6,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "CO2",
    "kode": "170",
    "id": "170"
  },
  {
    "no": null,
    "ruangan": "Monitor NETRE LT.6",
    "gedung": "POP/NETRE",
    "lantai": 6,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "Dry Cemical Powder",
    "kode": "171",
    "id": "171"
  },
  {
    "no": null,
    "ruangan": "Lobby NETRE LT.7",
    "gedung": "POP/NETRE",
    "lantai": 7,
    "merk": "FIREFIX",
    "kapasitas": "5 kg",
    "jenisGas": "CO2",
    "kode": "172",
    "id": "172"
  },
  {
    "no": null,
    "ruangan": "Mesin Lift NETRE LT.7",
    "gedung": "POP/NETRE",
    "lantai": 7,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "CO2",
    "kode": "173",
    "id": "173"
  },
  {
    "no": null,
    "ruangan": "DICO Neucentrix LT.1",
    "gedung": "NEUCENTRIX",
    "lantai": 1,
    "merk": "FIREFIX",
    "kapasitas": "3,5 kg",
    "jenisGas": "Dry Cemical Powder",
    "kode": "174",
    "id": "174"
  },
  {
    "no": null,
    "ruangan": "DICO Neucentrix LT.1",
    "gedung": "NEUCENTRIX",
    "lantai": 1,
    "merk": "BUCKEYE",
    "kapasitas": "3,5 kg",
    "jenisGas": "CO2",
    "kode": "175",
    "id": "175"
  },
  {
    "no": null,
    "ruangan": "DICO Neucentrix LT.1",
    "gedung": "NEUCENTRIX",
    "lantai": 1,
    "merk": "BUCKEYE",
    "kapasitas": "5 kg",
    "jenisGas": "CO2",
    "kode": "176",
    "id": "176"
  },
  {
    "no": null,
    "ruangan": "Lorong Neucentrix LT.1",
    "gedung": "NEUCENTRIX",
    "lantai": 1,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "Dry Cemical Powder",
    "kode": "177",
    "id": "177"
  },
  {
    "no": null,
    "ruangan": "TELIN Neucentrix LT.1",
    "gedung": "NEUCENTRIX",
    "lantai": 1,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "CO2",
    "kode": "178",
    "id": "178"
  },
  {
    "no": null,
    "ruangan": "IPTV Neucentrix LT.1",
    "gedung": "NEUCENTRIX",
    "lantai": 1,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "CO2",
    "kode": "179",
    "id": "179"
  },
  {
    "no": null,
    "ruangan": "Baterai Neucentrix LT.1",
    "gedung": "NEUCENTRIX",
    "lantai": 1,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "CO2",
    "kode": "180",
    "id": "180"
  },
  {
    "no": null,
    "ruangan": "Lobby Neucentrix LT.1",
    "gedung": "NEUCENTRIX",
    "lantai": 1,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "Dry Cemical Powder",
    "kode": "181",
    "id": "181"
  },
  {
    "no": null,
    "ruangan": "Sentral Neucentrix LT.1",
    "gedung": "NEUCENTRIX",
    "lantai": 1,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "CO2",
    "kode": "182",
    "id": "182"
  },
  {
    "no": null,
    "ruangan": "Sentral Neucentrix LT.1",
    "gedung": "NEUCENTRIX",
    "lantai": 1,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "CO2",
    "kode": "183",
    "id": "183"
  },
  {
    "no": null,
    "ruangan": "Sentral Neucentrix LT.1",
    "gedung": "NEUCENTRIX",
    "lantai": 1,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "CO2",
    "kode": "184",
    "id": "184"
  },
  {
    "no": null,
    "ruangan": "Lobby Neucentrix LT.1",
    "gedung": "NEUCENTRIX",
    "lantai": 1,
    "merk": "FIREFIX",
    "kapasitas": "5 kg",
    "jenisGas": "CO2",
    "kode": "185",
    "id": "185"
  },
  {
    "no": null,
    "ruangan": "Lobby Neucentrix LT.1",
    "gedung": "NEUCENTRIX",
    "lantai": 1,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "CO2",
    "kode": "186",
    "id": "186"
  },
  {
    "no": null,
    "ruangan": "Netra ARNET",
    "gedung": "ARNET",
    "lantai": null,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "Dry Cemical Powder",
    "kode": "187",
    "id": "187"
  },
  {
    "no": null,
    "ruangan": "Lobby ARNET",
    "gedung": "ARNET",
    "lantai": null,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "Dry Cemical Powder",
    "kode": "188",
    "id": "188"
  },
  {
    "no": null,
    "ruangan": "Pantry ARNET",
    "gedung": "ARNET",
    "lantai": null,
    "merk": "FIREFIX",
    "kapasitas": "5 kg",
    "jenisGas": "CO2",
    "kode": "189",
    "id": "189"
  },
  {
    "no": null,
    "ruangan": "Depan Mushola ARNET",
    "gedung": "ARNET",
    "lantai": null,
    "merk": "FIREFIX",
    "kapasitas": "5 kg",
    "jenisGas": "CO2",
    "kode": "190",
    "id": "190"
  },
  {
    "no": null,
    "ruangan": "Repair MODEM ARNET",
    "gedung": "ARNET",
    "lantai": null,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "Dry Cemical Powder",
    "kode": "191",
    "id": "191"
  },
  {
    "no": null,
    "ruangan": "Repair MODEM ARNET",
    "gedung": "ARNET",
    "lantai": null,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "CO2",
    "kode": "192",
    "id": "192"
  },
  {
    "no": null,
    "ruangan": "Lobby Timur OPMC LT.1",
    "gedung": "OPMC",
    "lantai": null,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "Dry Cemical Powder",
    "kode": "193",
    "id": "193"
  },
  {
    "no": null,
    "ruangan": "Lobby Barat OPMC LT.1",
    "gedung": "OPMC",
    "lantai": null,
    "merk": "FIREFIX",
    "kapasitas": "3,5 kg",
    "jenisGas": "Dry Cemical Powder",
    "kode": "194",
    "id": "194"
  },
  {
    "no": null,
    "ruangan": "Lorong OPMC LT.1",
    "gedung": "OPMC",
    "lantai": null,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "Dry Cemical Powder",
    "kode": "195",
    "id": "195"
  },
  {
    "no": null,
    "ruangan": "Lorong OPMC LT.1",
    "gedung": "OPMC",
    "lantai": null,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "Dry Cemical Powder",
    "kode": "196",
    "id": "196"
  },
  {
    "no": null,
    "ruangan": "Gudang Log SBU OPMC LT.1",
    "gedung": "OPMC",
    "lantai": null,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "CO2",
    "kode": "197",
    "id": "197"
  },
  {
    "no": null,
    "ruangan": "Gudang Log SBU OPMC LT.1",
    "gedung": "OPMC",
    "lantai": null,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "Dry Cemical Powder",
    "kode": "198",
    "id": "198"
  },
  {
    "no": null,
    "ruangan": "Gudang TA OPMC LT.1",
    "gedung": "OPMC",
    "lantai": null,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "CO2",
    "kode": "199",
    "id": "199"
  },
  {
    "no": null,
    "ruangan": "Lobby Timur OPMC LT.2",
    "gedung": "OPMC",
    "lantai": null,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "Dry Cemical Powder",
    "kode": "200",
    "id": "200"
  },
  {
    "no": null,
    "ruangan": "Koridor OPMC LT.2",
    "gedung": "OPMC",
    "lantai": null,
    "merk": "FIREFIX",
    "kapasitas": "3,5 kg",
    "jenisGas": "Dry Cemical Powder",
    "kode": "201",
    "id": "201"
  },
  {
    "no": null,
    "ruangan": "Staff OPMC LT.2",
    "gedung": "OPMC",
    "lantai": null,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "CO2",
    "kode": null,
    "id": "row93"
  },
  {
    "no": null,
    "ruangan": "Lobby Barat OPMC LT.2",
    "gedung": "OPMC",
    "lantai": null,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "Dry Cemical Powder",
    "kode": null,
    "id": "row94"
  },
  {
    "no": null,
    "ruangan": "Lobby Timur OPMC LT.3",
    "gedung": "OPMC",
    "lantai": null,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "Dry Cemical Powder",
    "kode": null,
    "id": "row95"
  },
  {
    "no": null,
    "ruangan": "Staff OPMC LT.3",
    "gedung": "OPMC",
    "lantai": null,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "Dry Cemical Powder",
    "kode": null,
    "id": "row96"
  },
  {
    "no": null,
    "ruangan": "Staff OPMC LT.3",
    "gedung": "OPMC",
    "lantai": null,
    "merk": "FIREFIX",
    "kapasitas": "3,5 kg",
    "jenisGas": "Dry Cemical Powder",
    "kode": null,
    "id": "row97"
  },
  {
    "no": null,
    "ruangan": "Lobby Barat OPMC LT.3",
    "gedung": "OPMC",
    "lantai": null,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "Dry Cemical Powder",
    "kode": null,
    "id": "row98"
  },
  {
    "no": null,
    "ruangan": "Lobby Timur OPMC LT.4",
    "gedung": "OPMC",
    "lantai": null,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "Dry Cemical Powder",
    "kode": null,
    "id": "row99"
  },
  {
    "no": null,
    "ruangan": "Koridor OPMC LT.4",
    "gedung": "OPMC",
    "lantai": null,
    "merk": "FIREFIX",
    "kapasitas": "3,5 kg",
    "jenisGas": "Dry Cemical Powder",
    "kode": null,
    "id": "row100"
  },
  {
    "no": null,
    "ruangan": "SISFO OPMC LT.4",
    "gedung": "OPMC",
    "lantai": null,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "CO2",
    "kode": null,
    "id": "row101"
  },
  {
    "no": null,
    "ruangan": "SISFO OPMC LT.4",
    "gedung": "OPMC",
    "lantai": null,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "CO2",
    "kode": null,
    "id": "row102"
  },
  {
    "no": null,
    "ruangan": "Lobby Barat OPMC LT.4",
    "gedung": "OPMC",
    "lantai": null,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "Dry Cemical Powder",
    "kode": null,
    "id": "row103"
  },
  {
    "no": null,
    "ruangan": "Genset 1 Netre SITE PLANE 1",
    "gedung": "UTILITY",
    "lantai": null,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "CO2",
    "kode": null,
    "id": "row104"
  },
  {
    "no": null,
    "ruangan": "Genset 1 Netre SITE PLANE 1",
    "gedung": "UTILITY",
    "lantai": null,
    "merk": "BUCKEYE",
    "kapasitas": "125 Lb",
    "jenisGas": "Dry Cemical Powder",
    "kode": null,
    "id": "row105"
  },
  {
    "no": null,
    "ruangan": "MDP 1 Netre SITE PLANE 1",
    "gedung": "UTILITY",
    "lantai": null,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "CO2",
    "kode": null,
    "id": "row106"
  },
  {
    "no": null,
    "ruangan": "MDP 1 Netre SITE PLANE 1",
    "gedung": "UTILITY",
    "lantai": null,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "CO2",
    "kode": null,
    "id": "row107"
  },
  {
    "no": null,
    "ruangan": "Genset 2 Netre SITE PLANE 1",
    "gedung": "UTILITY",
    "lantai": null,
    "merk": "BUCKEYE",
    "kapasitas": "125 Lb",
    "jenisGas": "Dry Cemical Powder",
    "kode": null,
    "id": "row108"
  },
  {
    "no": null,
    "ruangan": "Genset 2 Netre SITE PLANE 1",
    "gedung": "UTILITY",
    "lantai": null,
    "merk": "FIREFIX",
    "kapasitas": "5 kg",
    "jenisGas": "CO2",
    "kode": null,
    "id": "row109"
  },
  {
    "no": null,
    "ruangan": "MDP 2 Netre SITE PLANE 1",
    "gedung": "UTILITY",
    "lantai": null,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "CO2",
    "kode": null,
    "id": "row110"
  },
  {
    "no": null,
    "ruangan": "Genset flexi SITE PLANE 1",
    "gedung": "UTILITY",
    "lantai": null,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "Dry Cemical Powder",
    "kode": null,
    "id": "row111"
  },
  {
    "no": null,
    "ruangan": "Genset flexi SITE PLANE 1",
    "gedung": "UTILITY",
    "lantai": null,
    "merk": "FIREFIX",
    "kapasitas": "5 kg",
    "jenisGas": "CO2",
    "kode": null,
    "id": "row112"
  },
  {
    "no": null,
    "ruangan": "MDP flexi SITE PLANE 1",
    "gedung": "UTILITY",
    "lantai": null,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "CO2",
    "kode": null,
    "id": "row113"
  },
  {
    "no": null,
    "ruangan": "Trafo flexi SITE PLANE 1",
    "gedung": "UTILITY",
    "lantai": null,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "CO2",
    "kode": null,
    "id": "row114"
  },
  {
    "no": null,
    "ruangan": "CME SITE PLANE 1",
    "gedung": "UTILITY",
    "lantai": null,
    "merk": "FIREFIX",
    "kapasitas": "3,5 kg",
    "jenisGas": "Dry Cemical Powder",
    "kode": null,
    "id": "row115"
  },
  {
    "no": null,
    "ruangan": "Genset OPMC SITE PLANE 2",
    "gedung": "UTILITY",
    "lantai": null,
    "merk": "BUCKEYE",
    "kapasitas": "125 Lb",
    "jenisGas": "Dry Cemical Powder",
    "kode": null,
    "id": "row116"
  },
  {
    "no": null,
    "ruangan": "Trafo OPMC SITE PLANE 3",
    "gedung": "UTILITY",
    "lantai": null,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "CO2",
    "kode": null,
    "id": "row117"
  },
  {
    "no": null,
    "ruangan": "Rumah Pompa OPMCSITE PLANE 3",
    "gedung": "UTILITY",
    "lantai": null,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "CO2",
    "kode": null,
    "id": "row118"
  },
  {
    "no": null,
    "ruangan": "WARE HOUSE TA WARE HOUSE",
    "gedung": "WAREHOUSE",
    "lantai": null,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "Dry Cemical Powder",
    "kode": null,
    "id": "row119"
  },
  {
    "no": null,
    "ruangan": "WARE HOUSE TA WARE HOUSE ",
    "gedung": "WAREHOUSE",
    "lantai": null,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "Dry Cemical Powder",
    "kode": null,
    "id": "row120"
  },
  {
    "no": null,
    "ruangan": "WARE HOUSE TA WARE HOUSE",
    "gedung": "WAREHOUSE",
    "lantai": null,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "Dry Cemical Powder",
    "kode": null,
    "id": "row121"
  },
  {
    "no": null,
    "ruangan": "WARE HOUSE TA WARE HOUSE",
    "gedung": "WAREHOUSE",
    "lantai": null,
    "merk": "BUCKEYE",
    "kapasitas": "10 Lb",
    "jenisGas": "CO2",
    "kode": null,
    "id": "row122"
  },
  {
    "no": null,
    "ruangan": "Gudang NTE WARE HOUSE",
    "gedung": "WAREHOUSE",
    "lantai": null,
    "merk": "FIREFIX",
    "kapasitas": "5 kg",
    "jenisGas": "CO2",
    "kode": null,
    "id": "row123"
  },
  {
    "no": null,
    "ruangan": "Gudang NTE WARE HOUSE",
    "gedung": "WAREHOUSE",
    "lantai": null,
    "merk": "FIREFIX",
    "kapasitas": "5 kg",
    "jenisGas": "CO2",
    "kode": null,
    "id": "row124"
  },
  {
    "no": null,
    "ruangan": "Koridor WARE HOUSE",
    "gedung": "WAREHOUSE",
    "lantai": null,
    "merk": "FIREFIX",
    "kapasitas": "5 kg",
    "jenisGas": "CO2",
    "kode": null,
    "id": "row125"
  },
  {
    "no": null,
    "ruangan": "Pantry WARE HOUSE",
    "gedung": "WAREHOUSE",
    "lantai": null,
    "merk": "FIREFIX",
    "kapasitas": "3,5 kg",
    "jenisGas": "Dry Cemical Powder",
    "kode": null,
    "id": "row126"
  },
  {
    "no": null,
    "ruangan": "GSD BELAKANG",
    "gedung": "GSD",
    "lantai": null,
    "merk": "FIREFIX",
    "kapasitas": "3,5 kg",
    "jenisGas": "Dry Cemical Powder",
    "kode": null,
    "id": "row127"
  },
  {
    "no": null,
    "ruangan": "GSD BELAKANG",
    "gedung": "GSD",
    "lantai": null,
    "merk": "FIREFIX",
    "kapasitas": "5 kg",
    "jenisGas": "CO2",
    "kode": null,
    "id": "row128"
  }
];

if (typeof module !== "undefined") { module.exports = APAR_DATA; }
