// ==========================================================================
// data.js — Data Master APAR & FSS (1 - 128)
// Format Standar Berdasarkan Tabel Inspeksi APAR
// Setiap baris memiliki Kode Unik 1 sampai 128 dengan QR & Barcode
// ==========================================================================

const APAR_DATA = [
  { no: 1, kode: "1", id: "1", ruangan: "Pos Security NETRE LT.1", gedung: "POP/NETRE", lantai: 1, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "Dry Chemical Powder" },
  { no: 2, kode: "2", id: "2", ruangan: "Pos Security NETRE LT.1", gedung: "POP/NETRE", lantai: 1, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "CO2" },
  { no: 3, kode: "3", id: "3", ruangan: "TERAS NETRE LT.1", gedung: "POP/NETRE", lantai: 1, merk: "BUCKEYE", kapasitas: "125 Lb", jenisGas: "Dry Chemical Powder" },
  { no: 4, kode: "4", id: "4", ruangan: "Lobby NETRE LT.1", gedung: "POP/NETRE", lantai: 1, merk: "FIREFIX", kapasitas: "5 Kg", jenisGas: "CO2" },
  { no: 5, kode: "5", id: "5", ruangan: "MDF NETRE LT.1", gedung: "POP/NETRE", lantai: 1, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "Dry Chemical Powder" },
  { no: 6, kode: "6", id: "6", ruangan: "MDF NETRE LT.1", gedung: "POP/NETRE", lantai: 1, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "CO2" },
  { no: 7, kode: "7", id: "7", ruangan: "Rectifier NETRE LT.1", gedung: "POP/NETRE", lantai: 1, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "Dry Chemical Powder" },
  { no: 8, kode: "8", id: "8", ruangan: "Rectifier NETRE LT.1", gedung: "POP/NETRE", lantai: 1, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "CO2" },
  { no: 9, kode: "9", id: "9", ruangan: "Rectifier NETRE LT.1", gedung: "POP/NETRE", lantai: 1, merk: "FIREFIX", kapasitas: "5 Kg", jenisGas: "CO2" },
  { no: 10, kode: "10", id: "10", ruangan: "Trafo NETRE LT.1", gedung: "POP/NETRE", lantai: 1, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "Dry Chemical Powder" },
  { no: 11, kode: "11", id: "11", ruangan: "Cubical NETRE LT.1", gedung: "POP/NETRE", lantai: 1, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "CO2" },
  { no: 12, kode: "12", id: "12", ruangan: "Baterai Kering 1 NETRE LT.1", gedung: "POP/NETRE", lantai: 1, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "Dry Chemical Powder" },
  { no: 13, kode: "13", id: "13", ruangan: "Baterai Kering 1 NETRE LT.1", gedung: "POP/NETRE", lantai: 1, merk: "FIREFIX", kapasitas: "5 Kg", jenisGas: "CO2" },
  { no: 14, kode: "14", id: "14", ruangan: "Baterai Basah 1 NETRE LT.1", gedung: "POP/NETRE", lantai: 1, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "Dry Chemical Powder" },
  { no: 15, kode: "15", id: "15", ruangan: "Baterai Kering 2 NETRE LT.1", gedung: "POP/NETRE", lantai: 1, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "Dry Chemical Powder" },
  { no: 16, kode: "16", id: "16", ruangan: "Baterai Kering 2 NETRE LT.1", gedung: "POP/NETRE", lantai: 1, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "CO2" },
  { no: 17, kode: "17", id: "17", ruangan: "Lobby NETRE LT.2", gedung: "POP/NETRE", lantai: 2, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "CO2" },
  { no: 18, kode: "18", id: "18", ruangan: "UPS NETRE LT.2", gedung: "POP/NETRE", lantai: 2, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "CO2" },
  { no: 19, kode: "19", id: "19", ruangan: "STP NETRE LT.2", gedung: "POP/NETRE", lantai: 2, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "CO2" },
  { no: 20, kode: "20", id: "20", ruangan: "Koridor NETRE LT.2", gedung: "POP/NETRE", lantai: 2, merk: "FIREFIX", kapasitas: "5 Kg", jenisGas: "CO2" },
  { no: 21, kode: "21", id: "21", ruangan: "OLT NETRE LT.2", gedung: "POP/NETRE", lantai: 2, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "CO2" },
  { no: 22, kode: "22", id: "22", ruangan: "FTM NETRE LT.2", gedung: "POP/NETRE", lantai: 2, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "CO2" },
  { no: 23, kode: "23", id: "23", ruangan: "Lobby NETRE LT.3", gedung: "POP/NETRE", lantai: 3, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "Dry Chemical Powder" },
  { no: 24, kode: "24", id: "24", ruangan: "Data Center NETRE LT.3", gedung: "POP/NETRE", lantai: 3, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "CO2" },
  { no: 25, kode: "25", id: "25", ruangan: "Data Center NETRE LT.3", gedung: "POP/NETRE", lantai: 3, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "CO2" },
  { no: 26, kode: "26", id: "26", ruangan: "Data Center NETRE LT.3", gedung: "POP/NETRE", lantai: 3, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "CO2" },
  { no: 27, kode: "27", id: "27", ruangan: "Data Center NETRE LT.3", gedung: "POP/NETRE", lantai: 3, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "CO2" },
  { no: 28, kode: "28", id: "28", ruangan: "Data Center NETRE LT.3", gedung: "POP/NETRE", lantai: 3, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "CO2" },
  { no: 29, kode: "29", id: "29", ruangan: "NGN NETRE LT.3", gedung: "POP/NETRE", lantai: 3, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "CO2" },
  { no: 30, kode: "30", id: "30", ruangan: "NGN NETRE LT.3", gedung: "POP/NETRE", lantai: 3, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "CO2" },
  { no: 31, kode: "31", id: "31", ruangan: "NGN NETRE LT.3", gedung: "POP/NETRE", lantai: 3, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "CO2" },
  { no: 32, kode: "32", id: "32", ruangan: "NGN NETRE LT.3", gedung: "POP/NETRE", lantai: 3, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "CO2" },
  { no: 33, kode: "33", id: "33", ruangan: "Panel NETRE LT.3", gedung: "POP/NETRE", lantai: 3, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "CO2" },
  { no: 34, kode: "34", id: "34", ruangan: "Panel NETRE LT.3", gedung: "POP/NETRE", lantai: 3, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "Dry Chemical Powder" },
  { no: 35, kode: "35", id: "35", ruangan: "Lobby NETRE LT.4", gedung: "POP/NETRE", lantai: 4, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "CO2" },
  { no: 36, kode: "36", id: "36", ruangan: "Personil NETRE LT.4", gedung: "POP/NETRE", lantai: 4, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "Dry Chemical Powder" },
  { no: 37, kode: "37", id: "37", ruangan: "Sentral NETRE LT.4", gedung: "POP/NETRE", lantai: 4, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "CO2" },
  { no: 38, kode: "38", id: "38", ruangan: "Sentral NETRE LT.4", gedung: "POP/NETRE", lantai: 4, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "CO2" },
  { no: 39, kode: "39", id: "39", ruangan: "Flexi NETRE LT.4", gedung: "POP/NETRE", lantai: 4, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "CO2" },
  { no: 40, kode: "40", id: "40", ruangan: "Flexi NETRE LT.4", gedung: "POP/NETRE", lantai: 4, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "CO2" },
  { no: 41, kode: "41", id: "41", ruangan: "Metro NETRE LT.4", gedung: "POP/NETRE", lantai: 4, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "CO2" },
  { no: 42, kode: "42", id: "42", ruangan: "Metro NETRE LT.4", gedung: "POP/NETRE", lantai: 4, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "CO2" },
  { no: 43, kode: "43", id: "43", ruangan: "Lobby NETRE LT.5", gedung: "POP/NETRE", lantai: 5, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "CO2" },
  { no: 44, kode: "44", id: "44", ruangan: "Personil NETRE LT.5", gedung: "POP/NETRE", lantai: 5, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "Dry Chemical Powder" },
  { no: 45, kode: "45", id: "45", ruangan: "BTS Flexi NETRE LT.5", gedung: "POP/NETRE", lantai: 5, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "CO2" },
  { no: 46, kode: "46", id: "46", ruangan: "Space NETRE LT.5", gedung: "POP/NETRE", lantai: 5, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "CO2" },
  { no: 47, kode: "47", id: "47", ruangan: "Monitoring NETRE LT.5", gedung: "POP/NETRE", lantai: 5, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "CO2" },
  { no: 48, kode: "48", id: "48", ruangan: "Transmisi NETRE LT.5", gedung: "POP/NETRE", lantai: 5, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "CO2" },
  { no: 49, kode: "49", id: "49", ruangan: "Transmisi NETRE LT.5", gedung: "POP/NETRE", lantai: 5, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "CO2" },
  { no: 50, kode: "50", id: "50", ruangan: "Lobby NETRE LT.6", gedung: "POP/NETRE", lantai: 6, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "CO2" },
  { no: 51, kode: "51", id: "51", ruangan: "Personil NETRE LT.6", gedung: "POP/NETRE", lantai: 6, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "Dry Chemical Powder" },
  { no: 52, kode: "52", id: "52", ruangan: "Lorong NETRE LT.6", gedung: "POP/NETRE", lantai: 6, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "CO2" },
  { no: 53, kode: "53", id: "53", ruangan: "Lorong NETRE LT.6", gedung: "POP/NETRE", lantai: 6, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "CO2" },
  { no: 54, kode: "54", id: "54", ruangan: "Lorong NETRE LT.6", gedung: "POP/NETRE", lantai: 6, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "CO2" },
  { no: 55, kode: "55", id: "55", ruangan: "Lorong NETRE LT.6", gedung: "POP/NETRE", lantai: 6, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "CO2" },
  { no: 56, kode: "56", id: "56", ruangan: "IPTV NETRE LT.6", gedung: "POP/NETRE", lantai: 6, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "CO2" },
  { no: 57, kode: "57", id: "57", ruangan: "IPTV NETRE LT.6", gedung: "POP/NETRE", lantai: 6, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "CO2" },
  { no: 58, kode: "58", id: "58", ruangan: "NGN NETRE LT.6", gedung: "POP/NETRE", lantai: 6, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "CO2" },
  { no: 59, kode: "59", id: "59", ruangan: "NGN NETRE LT.6", gedung: "POP/NETRE", lantai: 6, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "CO2" },
  { no: 60, kode: "60", id: "60", ruangan: "NGN NETRE LT.6", gedung: "POP/NETRE", lantai: 6, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "CO2" },
  { no: 61, kode: "61", id: "61", ruangan: "Monitor NETRE LT.6", gedung: "POP/NETRE", lantai: 6, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "CO2" },
  { no: 62, kode: "62", id: "62", ruangan: "Monitor NETRE LT.6", gedung: "POP/NETRE", lantai: 6, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "Dry Chemical Powder" },
  { no: 63, kode: "63", id: "63", ruangan: "Lobby NETRE LT.7", gedung: "POP/NETRE", lantai: 7, merk: "FIREFIX", kapasitas: "5 Kg", jenisGas: "CO2" },
  { no: 64, kode: "64", id: "64", ruangan: "Mesin Lift NETRE LT.7", gedung: "POP/NETRE", lantai: 7, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "CO2" },
  { no: 65, kode: "65", id: "65", ruangan: "DICO NeuCentriX LT.1", gedung: "NEUCENTRIX", lantai: 1, merk: "FIREFIX", kapasitas: "3.5 Kg", jenisGas: "Dry Chemical Powder" },
  { no: 66, kode: "66", id: "66", ruangan: "DICO NeuCentriX LT.1", gedung: "NEUCENTRIX", lantai: 1, merk: "BUCKEYE", kapasitas: "3.5 Kg", jenisGas: "CO2" },
  { no: 67, kode: "67", id: "67", ruangan: "DECO NeuCentriX LT.1", gedung: "NEUCENTRIX", lantai: 1, merk: "BUCKEYE", kapasitas: "5 Kg", jenisGas: "CO2" },
  { no: 68, kode: "68", id: "68", ruangan: "Lorong NeuCentriX LT.1", gedung: "NEUCENTRIX", lantai: 1, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "Dry Chemical Powder" },
  { no: 69, kode: "69", id: "69", ruangan: "TELIN NeuCentriX LT.1", gedung: "NEUCENTRIX", lantai: 1, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "CO2" },
  { no: 70, kode: "70", id: "70", ruangan: "IPTV NeuCentriX LT.1", gedung: "NEUCENTRIX", lantai: 1, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "CO2" },
  { no: 71, kode: "71", id: "71", ruangan: "Baterai NeuCentriX LT.1", gedung: "NEUCENTRIX", lantai: 1, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "CO2" },
  { no: 72, kode: "72", id: "72", ruangan: "Lobby NeuCentriX LT.1", gedung: "NEUCENTRIX", lantai: 1, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "Dry Chemical Powder" },
  { no: 73, kode: "73", id: "73", ruangan: "Sentral NeuCentriX LT.1", gedung: "NEUCENTRIX", lantai: 1, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "CO2" },
  { no: 74, kode: "74", id: "74", ruangan: "Sentral NeuCentriX LT.1", gedung: "NEUCENTRIX", lantai: 1, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "CO2" },
  { no: 75, kode: "75", id: "75", ruangan: "Sentral NeuCentriX LT.1", gedung: "NEUCENTRIX", lantai: 1, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "CO2" },
  { no: 76, kode: "76", id: "76", ruangan: "Lobby NeuCentriX LT.1", gedung: "NEUCENTRIX", lantai: 1, merk: "FIREFIX", kapasitas: "5 Kg", jenisGas: "CO2" },
  { no: 77, kode: "77", id: "77", ruangan: "Lobby NeuCentriX LT.1", gedung: "NEUCENTRIX", lantai: 1, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "CO2" },
  { no: 78, kode: "78", id: "78", ruangan: "Netra ARNET", gedung: "ARNET", lantai: 1, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "Dry Chemical Powder" },
  { no: 79, kode: "79", id: "79", ruangan: "Lobby ARNET", gedung: "ARNET", lantai: 1, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "Dry Chemical Powder" },
  { no: 80, kode: "80", id: "80", ruangan: "Pantry ARNET", gedung: "ARNET", lantai: 1, merk: "FIREFIX", kapasitas: "5 Kg", jenisGas: "CO2" },
  { no: 81, kode: "81", id: "81", ruangan: "Depan Mushola ARNET", gedung: "ARNET", lantai: 1, merk: "FIREFIX", kapasitas: "5 Kg", jenisGas: "CO2" },
  { no: 82, kode: "82", id: "82", ruangan: "Repair MODEM ARNET", gedung: "ARNET", lantai: 1, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "Dry Chemical Powder" },
  { no: 83, kode: "83", id: "83", ruangan: "Repair MODEM ARNET", gedung: "ARNET", lantai: 1, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "CO2" },
  { no: 84, kode: "84", id: "84", ruangan: "Lobby Timur OPMC LT.1", gedung: "OPMC", lantai: 1, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "Dry Chemical Powder" },
  { no: 85, kode: "85", id: "85", ruangan: "Lobby Barat OPMC LT.1", gedung: "OPMC", lantai: 1, merk: "FIREFIX", kapasitas: "3.5 Kg", jenisGas: "Dry Chemical Powder" },
  { no: 86, kode: "86", id: "86", ruangan: "Lorong OPMC LT.1", gedung: "OPMC", lantai: 1, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "Dry Chemical Powder" },
  { no: 87, kode: "87", id: "87", ruangan: "Lorong OPMC LT.1", gedung: "OPMC", lantai: 1, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "Dry Chemical Powder" },
  { no: 88, kode: "88", id: "88", ruangan: "Gudang Log SBU OPMC LT.1", gedung: "OPMC", lantai: 1, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "CO2" },
  { no: 89, kode: "89", id: "89", ruangan: "Gudang Log SBU OPMC LT.1", gedung: "OPMC", lantai: 1, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "Dry Chemical Powder" },
  { no: 90, kode: "90", id: "90", ruangan: "Gudang TA OPMC LT.1", gedung: "OPMC", lantai: 1, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "CO2" },
  { no: 91, kode: "91", id: "91", ruangan: "Lobby Timur OPMC LT.2", gedung: "OPMC", lantai: 2, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "Dry Chemical Powder" },
  { no: 92, kode: "92", id: "92", ruangan: "Koridor OPMC LT.2", gedung: "OPMC", lantai: 2, merk: "FIREFIX", kapasitas: "3.5 Kg", jenisGas: "Dry Chemical Powder" },
  { no: 93, kode: "93", id: "93", ruangan: "Staff OPMC LT.2", gedung: "OPMC", lantai: 2, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "CO2" },
  { no: 94, kode: "94", id: "94", ruangan: "Lobby Barat OPMC LT.2", gedung: "OPMC", lantai: 2, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "Dry Chemical Powder" },
  { no: 95, kode: "95", id: "95", ruangan: "Lobby Timur OPMC LT.3", gedung: "OPMC", lantai: 3, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "Dry Chemical Powder" },
  { no: 96, kode: "96", id: "96", ruangan: "Staff OPMC LT.3", gedung: "OPMC", lantai: 3, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "Dry Chemical Powder" },
  { no: 97, kode: "97", id: "97", ruangan: "Staff OPMC LT.3", gedung: "OPMC", lantai: 3, merk: "FIREFIX", kapasitas: "3.5 Kg", jenisGas: "Dry Chemical Powder" },
  { no: 98, kode: "98", id: "98", ruangan: "Lobby Barat OPMC LT.3", gedung: "OPMC", lantai: 3, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "Dry Chemical Powder" },
  { no: 99, kode: "99", id: "99", ruangan: "Lobby Timur OPMC LT.4", gedung: "OPMC", lantai: 4, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "Dry Chemical Powder" },
  { no: 100, kode: "100", id: "100", ruangan: "Koridor OPMC LT.4", gedung: "OPMC", lantai: 4, merk: "FIREFIX", kapasitas: "3.5 Kg", jenisGas: "Dry Chemical Powder" },
  { no: 101, kode: "101", id: "101", ruangan: "SISFO OPMC LT.4", gedung: "OPMC", lantai: 4, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "CO2" },
  { no: 102, kode: "102", id: "102", ruangan: "SISFO OPMC LT.4", gedung: "OPMC", lantai: 4, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "CO2" },
  { no: 103, kode: "103", id: "103", ruangan: "Lobby Barat OPMC LT.4", gedung: "OPMC", lantai: 4, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "Dry Chemical Powder" },
  { no: 104, kode: "104", id: "104", ruangan: "Genset 1 Netre SITE PLANE 1", gedung: "UTILITY", lantai: 1, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "CO2" },
  { no: 105, kode: "105", id: "105", ruangan: "Genset 1 Netre SITE PLANE 1", gedung: "UTILITY", lantai: 1, merk: "BUCKEYE", kapasitas: "125 Lb", jenisGas: "Dry Chemical Powder" },
  { no: 106, kode: "106", id: "106", ruangan: "MDP 1 Netre SITE PLANE 1", gedung: "UTILITY", lantai: 1, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "CO2" },
  { no: 107, kode: "107", id: "107", ruangan: "MDP 1 Netre SITE PLANE 1", gedung: "UTILITY", lantai: 1, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "CO2" },
  { no: 108, kode: "108", id: "108", ruangan: "Genset 2 Netre SITE PLANE 1", gedung: "UTILITY", lantai: 1, merk: "BUCKEYE", kapasitas: "125 Lb", jenisGas: "Dry Chemical Powder" },
  { no: 109, kode: "109", id: "109", ruangan: "Genset 2 Netre SITE PLANE 1", gedung: "UTILITY", lantai: 1, merk: "FIREFIX", kapasitas: "5 Kg", jenisGas: "CO2" },
  { no: 110, kode: "110", id: "110", ruangan: "MDP 2 Netre SITE PLANE 1", gedung: "UTILITY", lantai: 1, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "CO2" },
  { no: 111, kode: "111", id: "111", ruangan: "Genset flexi SITE PLANE 1", gedung: "UTILITY", lantai: 1, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "Dry Chemical Powder" },
  { no: 112, kode: "112", id: "112", ruangan: "Genset flexi SITE PLANE 1", gedung: "UTILITY", lantai: 1, merk: "FIREFIX", kapasitas: "5 Kg", jenisGas: "CO2" },
  { no: 113, kode: "113", id: "113", ruangan: "MDP flexi SITE PLANE 1", gedung: "UTILITY", lantai: 1, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "CO2" },
  { no: 114, kode: "114", id: "114", ruangan: "Trafo flexi SITE PLANE 1", gedung: "UTILITY", lantai: 1, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "CO2" },
  { no: 115, kode: "115", id: "115", ruangan: "CME SITE PLANE 1", gedung: "UTILITY", lantai: 1, merk: "FIREFIX", kapasitas: "3.5 Kg", jenisGas: "Dry Chemical Powder" },
  { no: 116, kode: "116", id: "116", ruangan: "Genset OPMC SITE PLANE 2", gedung: "UTILITY", lantai: 1, merk: "BUCKEYE", kapasitas: "125 Lb", jenisGas: "Dry Chemical Powder" },
  { no: 117, kode: "117", id: "117", ruangan: "Trafo OPMC SITE PLANE 3", gedung: "UTILITY", lantai: 1, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "CO2" },
  { no: 118, kode: "118", id: "118", ruangan: "Rumah Pompa OPMC SITE PLANE 3", gedung: "UTILITY", lantai: 1, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "CO2" },
  { no: 119, kode: "119", id: "119", ruangan: "WARE HOUSE TA WARE HOUSE", gedung: "WAREHOUSE", lantai: 1, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "Dry Chemical Powder" },
  { no: 120, kode: "120", id: "120", ruangan: "WARE HOUSE TA WARE HOUSE", gedung: "WAREHOUSE", lantai: 1, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "Dry Chemical Powder" },
  { no: 121, kode: "121", id: "121", ruangan: "WARE HOUSE TA WARE HOUSE", gedung: "WAREHOUSE", lantai: 1, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "Dry Chemical Powder" },
  { no: 122, kode: "122", id: "122", ruangan: "WARE HOUSE TA WARE HOUSE", gedung: "WAREHOUSE", lantai: 1, merk: "BUCKEYE", kapasitas: "10 Lb", jenisGas: "CO2" },
  { no: 123, kode: "123", id: "123", ruangan: "Gudang NTE WARE HOUSE", gedung: "WAREHOUSE", lantai: 1, merk: "FIREFIX", kapasitas: "5 Kg", jenisGas: "CO2" },
  { no: 124, kode: "124", id: "124", ruangan: "Gudang NTE WARE HOUSE", gedung: "WAREHOUSE", lantai: 1, merk: "FIREFIX", kapasitas: "5 Kg", jenisGas: "CO2" },
  { no: 125, kode: "125", id: "125", ruangan: "Koridor WARE HOUSE", gedung: "WAREHOUSE", lantai: 1, merk: "FIREFIX", kapasitas: "5 Kg", jenisGas: "CO2" },
  { no: 126, kode: "126", id: "126", ruangan: "Pantry WARE HOUSE", gedung: "WAREHOUSE", lantai: 1, merk: "FIREFIX", kapasitas: "3.5 Kg", jenisGas: "Dry Chemical Powder" },
  { no: 127, kode: "127", id: "127", ruangan: "GSD BELAKANG", gedung: "GSD", lantai: 1, merk: "FIREFIX", kapasitas: "3.5 Kg", jenisGas: "Dry Chemical Powder" },
  { no: 128, kode: "128", id: "128", ruangan: "GSD BELAKANG", gedung: "GSD", lantai: 1, merk: "FIREFIX", kapasitas: "5 Kg", jenisGas: "CO2" }
];

// Support for browser global and CommonJS / ES module export
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { APAR_DATA };
}
if (typeof window !== 'undefined') {
  window.APAR_DATA = APAR_DATA;
}
